### ISSUE TITLE
type cohesion / merging

### ISSUE THREAD

**Issue by gedw99** [gokit/cqrskit#1]
There are 2 choices and they affect the architecture alot so this is a thing to work out early.

Basically there is y.js, which is clock independent, because it uses crdt and hence context and counting. Not this is written in js, and so we would have to port to golang.
y.js does NOT use operational transform.

Here is a golang / JS implemenation that uses Operational Transform, but does not support offline.
https://github.com/Jeffail/leaps/blob/master/client/javascript/leapclient.js
For it to support offline, architecturally it will need ordering (because its not using context like CRDT), and so that means a Clock ( HLC) and also snowflakes UUID. 

BTW OT based implemenatiosn fit MUCH better with CQRS architectures, because an OT is realyl just a mutation. You can see this in Leaps where the mutations are shown:
https://github.com/Jeffail/leaps/blob/master/lib/api/README.md

Its very clean i think whats happening...

The problme with y.js and CRDT based systems is speed.
This can be gotten arond using Replicated Abstract Types
https://github.com/atom/teletype-crdt/pull/4
http://www.dtic.mil/dtic/tr/fulltext/u2/a153648.pdf

Then there is the Hybrid Logic clock.
CockroachDB has an implementation :)
https://github.com/cockroachdb/cockroach/blob/master/pkg/util/hlc/hlc.go
Suggest this be tested using a CLI to simulate a few users changing the same data type.

---

SO what to us :) ?
I woudl start with leaps as a basis to get going
https://github.com/Jeffail/leaps
Its clear whats going on with his, and its clear how to make it work for offline too:
https://github.com/Jeffail/leaps/issues/28
All you need to do is fo what every CQRS shoudl do and retain ALL messages that every go through the system forever. Its nice these two marry up so well.
Also by retaining the Leg of Messages it makes replication easy too right and backed and rebuilds of a cluster if everything goes boom. 

Now to make ordering tighter in terms of time, we discussed that alot.
lamport clock or other to get things ordered. If you dive into his code you can se where he reorders 
I would Definitly look at cockroach DB's HCL. Its battle proven and getting HC right is tough stuff.

Firebase and Couch DB  use LWW (Last Write Wins) and so are really simple. This is good enough for data you dont care about too much, but what a easy way out. 

Well if you look at sharedDB, you can start to see how there are side aspects to doing Consistency.
https://github.com/share/sharedb

Right now i think that a decent OT based approach with a HCL and Snowflake is good and fits the CRDT architecture too. 
CRDT can also be layered on top and i have seen that done.
This goes into using them together: https://news.ycombinator.com/item?id=13803843

**Comment by influx6** [comment]
I am quite intrested in HLC so will look into it tomorrow more closely,
especially the cockroachdb implementation.

Best Regards,
Alex A. Ewetumo.

Software Engineer
https://github.com/influx6 (trinoxf@gmail.com, Skype: trinoxf, Tel:
+2349053058679)

**Comment by gedw99** [comment]
ok dude. Have fun...

**Comment by influx6** [comment]
Also this issue is more related to CRDT than cqrs, though their is some connection.
